name: Run Maestro web tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils libgbm-dev

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: "stable"

      - name: Add Maestro to PATH
        run: echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Maestro Tests
        env:
          CHROME_ARGS: "--no-sandbox --disable-dev-shm-usage"
        run: maestro test web-flow.yaml
