name: Run Maestro web tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Add Maestro to PATH
        run: echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Maestro Tests
        run: maestro web-flow.yaml
